# Generated by Django 5.2.1 on 2025-05-30 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('SQL', 'SQL'), ('C++', 'C++')], max_length=20)),
                ('difficulty', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('question_type', models.CharField(choices=[('boolean', 'True/False'), ('single_choice', 'Single Choice (4 options)'), ('multiple_choice', 'Multiple Choice'), ('text', 'Text Answer')], max_length=20)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(blank=True, max_length=200)),
                ('option_b', models.CharField(blank=True, max_length=200)),
                ('option_c', models.CharField(blank=True, max_length=200)),
                ('option_d', models.CharField(blank=True, max_length=200)),
                ('option_e', models.CharField(blank=True, max_length=200)),
                ('correct_answer', models.TextField()),
                ('correct_boolean', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('questions', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizuser')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('total_time', models.DurationField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quizuser')),
            ],
        ),
    ]
